// Register a Service Worker.
if (!("serviceWorker" in navigator)) {
	alert("PWA not supported");
}

let sub = null;

// triggers navigator.serviceWorker.ready when done
navigator.serviceWorker.register("service-worker.js");

navigator.serviceWorker.ready.then(async function (registration) {
	// Use the PushManager to get the user's subscription to the push service.
	const subscription = await registration.pushManager.getSubscription();
	// If a subscription was found, return it.
	if (subscription) {
		sub = subscription;
		return subscription;
	}
	// Get the server's public key
	const response = await fetch("http://localhost:8888/publickey", {
		method: "GET",
	});
	const { publicKey } = await response.json();
	const convertedVapidKey = urlBase64ToUint8Array(publicKey);
	return await registration.pushManager.subscribe({
		userVisibleOnly: true,
		applicationServerKey: convertedVapidKey,
	});
});
// .then(function (subscription) {
// 	fetch("http://localhost:8888/registrations", {
// 		method: "post",
// 		headers: {
// 			"Content-type": "application/json",
// 		},
// 		body: JSON.stringify({
// 			subscription: subscription,
// 		}),
// 	});
// });

// This function is needed because Chrome doesn't accept a base64 encoded string
// as value for applicationServerKey in pushManager.subscribe yet
// https://bugs.chromium.org/p/chromium/issues/detail?id=802280
function urlBase64ToUint8Array(base64String) {
	var padding = "=".repeat((4 - (base64String.length % 4)) % 4);
	var base64 = (base64String + padding).replace(/\-/g, "+").replace(/_/g, "/");

	var rawData = window.atob(base64);
	var outputArray = new Uint8Array(rawData.length);

	for (var i = 0; i < rawData.length; ++i) {
		outputArray[i] = rawData.charCodeAt(i);
	}
	return outputArray;
}

document
	.getElementById("pdfUploadForm")
	.addEventListener("submit", async function (e) {
		e.preventDefault();

		const fileInput = document.getElementById("pdfFile");
		const statusMessage = document.getElementById("statusMessage");

		if (fileInput.files.length === 0) {
			statusMessage.style.color = "red";
			statusMessage.textContent = "Please select a file first.";
			return;
		}

		const file = fileInput.files[0];
		if (file.type !== "application/pdf") {
			statusMessage.style.color = "red";
			statusMessage.textContent = "Only PDF files are allowed.";
			return;
		}

		const formData = new FormData();
		formData.append("file", file);
		formData.append("subscription", JSON.stringify(sub));

		statusMessage.style.color = "blue";
		statusMessage.textContent = "Uploading...";

		try {
			const backendUrl = "http://localhost:8888/documents";

			const response = await fetch(backendUrl, {
				method: "POST",
				body: formData,
			});

			if (response.ok) {
				const result = await response.text();
				statusMessage.style.color = "green";
				statusMessage.textContent = "PDF uploaded successfully!";
			} else {
				statusMessage.style.color = "red";
				statusMessage.textContent = `Upload failed with status: ${response.status}`;
			}
		} catch (error) {
			statusMessage.style.color = "red";
			statusMessage.textContent = "An error occurred during upload.";
			console.error("Error:", error);
		}
	});

// document.getElementById("doIt").onclick = function () {
//   const delay = document.getElementById("notification-delay").value;
//   const ttl = document.getElementById("notification-ttl").value;

// Ask the server to send the client a notification (for testing purposes, in actual
// applications the push notification is likely going to be generated by some event
// in the server).
//     fetch("http://localhost:8888/notifications", {
//       method: "post",
//       headers: {
//         "Content-type": "application/json",
//       },
//       body: JSON.stringify({
//         subscription: subscription,
//         delay: delay,
//         ttl: ttl,
//       }),
//     });
//   };
// }).catch(console.error);
